<?

$basePath = '/media/win7/Movies/';
$allowedExtensions = array("mkv"=>1, "avi"=>1, "mp4"=>1, "flv"=>1);
$minimumSize = 100;

$searchLink1="http://www.bing.com/search?q=imdb+";
$searchLink2="http://www.bing.com/search?q=imdb+internet+movie+database+";

	$generalReplacement = array("\." => " ",
		"-"=>" ",
		"_"=>" ",
		"\["=>" [",
		"\]"=>"] ",
		"\("=>" (",
		"\) "=>") ",
		"\[.*\]" => "",
		"\{.*\}"=>"",
		"[0-9]+p"=>"",
		"[0-9]+mb"=>"",
		"Blu.?Ray"=>"",
		"xvid"=>"",
		"[dv\s]*d\s?rip"=>"",
		"[brd\s]*\s?rip"=>"",
		"dvd\s?"=>" ",
		"[\s]dvd[\s]?"=>" ",
		"[\s]eng[\s]?"=>"",
		"[\s]?hindi[\s]?"=>"",
		"\(.*\)"=>"",
		"[0-9]cd"=>"",
		"cd[0-9]"=>"",
		"x[0-9]+"=>"",
		"readnfo"=>"",
		"[\s]HD[\s]?"=>" ",
		"~[\S]+"=>"",
		"ac3"=>"",
		"h264"=>"",
		"m720"=>"",
		"r5"=>"",
		"26k"=>"",
		"[\s]ts[\s]?"=>" ",
		"Dual ?Audio"=>"",
		"unrated"=>"",
		"collectors ?edition"=>"",
		"director.{0,2}cut"=>"",
		"[\s]remastered[\s]? e?d?i?t?i?o?n?"=>"",
		"high ?definition"=>" "
		);

	$torrentReplacement = array("axxo"=>"",
		"[\s]?fxg[\s]"=>" ",
		"[\s]fxg[\s]?"=>" ",
		"[\s]?aac[\s]"=>" ",
		"[\s]aac[\s]?"=>" ",
		"[\s]?brg[\s]"=>" ",
		"[\s]brg[\s]?"=>" ",
		"[\s]?btw[\s]"=>" ",
		"[\s]btw[\s]?"=>" ",
		"[\s]?silu[\s]"=>" ",
		"[\s]silu[\s]?"=>" ",
		"[\s]?fxm[\s]"=>" ",
		"[\s]fxm[\s]?"=>" ",
		"[\s]?tdp[\s]"=>" ",
		"[\s]tdp[\s]?"=>" ",
		"[\s]?dmt[\s]"=>" ",
		"[\s]dmt[\s]?"=>" ",
		"[\s]?stv[\s]"=>" ",
		"[\s]stv[\s]?"=>" ",
		"[\s]?aymo[\s]"=>" ",
		"[\s]aymo[\s]?"=>" ",
		"[\s]?ftw[\s]"=>" ",
		"[\s]ftw[\s]?"=>" ",
		"[\s]?FÅM€[\s]"=>" ",
		"[\s]FÅM€[\s]?"=>" ",
		"[\s]?\$am3e[\s]"=>" ",
		"[\s]\$am3e[\s]?"=>" ",
		"[\s]?n0w0nd3r[\s]"=>" ",
		"[\s]n0w0nd3r[\s]?"=>" ",
		"[\s]?karina[\s]"=>" ",
		"[\s]karina[\s]?"=>" ",
		"[\s]?stealthmaster[\s]"=>" ",
		"[\s]stealthmaster[\s]?"=>" ",
		"[\s]?munchkinoid[\s]"=>" ",
		"[\s]munchkinoid[\s]?"=>" ",
		"[\s]?redalert[\s]"=>" ",
		"[\s]redalert[\s]?"=>" ",
		"[\s]?roboris[\s]"=>" ",
		"[\s]roboris[\s]?"=>" ",
		"[\s]?ganool[\s]"=>" ",
		"[\s]ganool[\s]?"=>" ",
		"[\s]?dtrg[\s]"=>" ",
		"[\s]dtrg[\s]?"=>" ",
		"[\s]?zeberzee[\s]"=>" ",
		"[\s]zeberzee[\s]?"=>" ",
		"[\s]?dizzle[\s]"=>" ",
		"[\s]dizzle[\s]?"=>" ",
		"[\s]scr[\s]?"=>" ",
		"yify"=>"",
		"saphire"=>"",
		"hasak"=>"",
		"btsfilms"=>"",
		"tokeup"=>"",
		"vlis"=>"",
		"3qhbppcec"=>""
		);
	$caseSensitiveReplacement = array("[\s]?[a-z]+[A-Z]+[a-z]+[\s]?"=>"",
		"[\s]?[A-Z]+[a-z]+[A-Z]+[\s]?"=>""
		);
?>